# Experiment
device_id: cuda
seed: 42
epochs: 3_000
log_every_n: 10 
update_every_n: 1

# Environment
env: "Pendulum-v1"

# Agent
svg0:
  lr: 3.0e-4
  gamma: 0.99
  buffer_steps: 2_000
  update_epochs: 3
  num_mini_batches: 256
  update_interval: 1
  hidden_sizes: [256, 256, 256, 256]
  # KL prior
  prior_obs_dim: 1
  prior_coeff: 0.05